### ISSUE TITLE
`level` should be an object or two fields

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-api#10]
Don’t join complexity and initiation together, use either loose fields on the module itself, or nest them in `level`.
For the values, I suggest numbers instead.

**Comment by Razpudding** [comment]
I don't think it's really clear yet how these will be used. Right now it seems they're interconnected so they together create one answer related to the level of the course. Because it's still unclear how it will be used I also think strings are better. That still allows you to send over numbers to the API, they'll just be stored as strings.
As with the issue of "sued/tested" I don't want to change it before knowing for sure it will stay the same.

**Comment by wooorm** [comment]
> Because it's still unclear how it will be used I also think strings are better.

How is it unclear? They are two separate fields in the form. We need two separate fields for the dashboard (to visualise the X and Y axes). Why join them together...

> That still allows you to send over numbers to the API, they'll just be stored as strings.

It requires stringifying (form) and parsing (dashboard) text to map it to the actual values. Whyyy? 🤷🏽‍♀️

**Comment by Razpudding** [comment]
The thing is that the values are likely to change. It's a new model wit vage labels like (re)productive. If you store them as numbers for year 2018-2019 and then in 2019-2020 you decide tit should be called 'constructive' you'd have to write fixes in your code.  It's even worse if you add a level in between. It's also highly unlikely that other programs will adopt the same terminology so I'd rather have to exclude one field from another programs course model than two.
I could nest them in level as you suggested earlier.

**Comment by wooorm** [comment]
> The thing is that the values are likely to change. It's a new model wit vage labels like (re)productive. If you store them as numbers for year 2018-2019 and then in 2019-2020 you decide it should be called 'constructive' you'd have to write fixes in your code.

It’s well-defined and based on literature (only changing the label zelfsturing to initierend vermogen to be more applicable to CMD, but other terms are from Coppoolse, R., Vroegindeweij, D. *Curriculumcasco een stappenplan voor de ontwikkeling van een competentiegerichte leeromgeving*. ROC Mondriaan, 2009).

> It's even worse if you add a level in between.

Sure, I don’t like `level` as an object either.
But that would allow other programs to add their own level definitions?

> It's also highly unlikely that other programs will adopt the same terminology so I'd rather have to exclude one field from another programs course model than two.

The fields work well for non-CMD programmes, so I don’t agree with that it’s *highly unlikely*.
This is also a problem already existing in many other fields.
Adding this isn’t going to make it *that much* worse!

**Comment by wooorm** [comment]
Solved in cmd-curriculum-api@next.
