### ISSUE TITLE
Use nicer array syntax

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-api#4]
https://github.com/cmda-the-lab/study-guide-api/blob/375af4983e9e9835f0f5180cd8ac0aa2449c9b8a/index.js#L112

Could be:

```js
  courses = Array.isArray(courses) ? courses : [courses]
```

**Comment by Razpudding** [comment]
Thanks! I'm planning to move that to some middleware so it can be reused.
