### ISSUE TITLE
Fix cluster data to move away from projects

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-api#5]

**Comment by Razpudding** [comment]
Hmm what's wrong with the data specifically? Sorry if this refers to something we discussed, can't seem to recall 🤔

**Comment by wooorm** [comment]
Some suggestions:

Schema:
* Could we use the phase ids [as seen here](https://github.com/cmda-the-lab/study-guide-frontend-input/blob/master/src/assets/program-phases.json)
* Could we add years (learning years), and maybe quarters (that way we can be smart about showing choice semesters or choice quarters)

Content: 
* Could we not use the word “Project” in the names? Think it’s too confusing and avoiding it would still be clear.

**Comment by Razpudding** [comment]
Fixed the schema phase property. It's now an enum with the values you suggested. It's kind of pain to edit all the clusters already in the system. I opted to change all the phase ids to the new english versions . We'll have to write a small program later that upserts clusters to update more info.

**Comment by wooorm** [comment]
Solved in cmd-curriculum-api@next.
