### ISSUE TITLE
Rename course to module

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-api#7]

**Comment by Razpudding** [comment]
Hmm yeah I've kind of been dreading this as it was embedded so deep into the system by te time we figured out what it should be called. I'll have to do this carefully in all aspects of the API and the DB. Will let you know when it's done so we can both test changes.
As it requires a database change it's not something I can just put in a separate branch, it'll have to be changed everywhere at the same time.

**Comment by wooorm** [comment]
Yep, I know, but I think it’s better to do it now than wait to do it after people start filling in more data.

**Comment by Razpudding** [comment]
Oh yeah I'm gonna do it, was just explaining why I hadn't so far (and why it's a critical thing).
