### ISSUE TITLE
New terms for *Learned / *Asked; *Required / *Used

### ISSUE THREAD

**Issue by wooorm** [cmda-the-lab/study-guide-api#9]
This seems rather random.
Maybe we can place objects in there, such as with an ISBN or a URL.

**Comment by Razpudding** [comment]
I thought we decided to go with "used" and "tested". Had a brief convo with Sonja about it. It's hard to explain in one word so maybe we should leave the word as it is but add a description to the questions in the frontend to explain it better.
If we go with those terms it's still not clear what is taught within a course. It feels like this is something to be hashed out with the curcom first and when a clear decision is made, the backend should be changed to reflect it.

**Comment by wooorm** [comment]
What I mean is that all these four terms are used. I suggest new terms.

Maybe *Taught / *Tested for product and research? Anyway, It’s hard, I dunno!

I think my actual problem here is that I feel two arrays are a weird way to store this information.
I suggest a list of objects for each of products, research, and resources.

Anyway, I don’t know how to do it yet, just feels confusing.

> so maybe we should leave the word as it is but add a description to the questions in the frontend to explain it better.

That’s already done!

**Comment by Razpudding** [comment]
To "solve" a number of these issues right now I would suggest the following:
As we don't know yet what terms we'll settle on in the future, leave them "dirty" as they are but agree on a deadline when all nomenclature should be clear. Then we can update all terms.

**Comment by wooorm** [comment]
Good idea! 👍

**Comment by wooorm** [comment]
Solved in cmd-curriculum-api@next.
